# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tailwindcss-rails` gem.
# Please instead update this file by running `bin/tapioca gem tailwindcss-rails`.

module Tailwindcss; end

module Tailwindcss::Commands
  class << self
    # source://tailwindcss-rails//lib/tailwindcss/commands.rb#58
    def compile_command(debug: T.unsafe(nil), **kwargs); end

    # source://tailwindcss-rails//lib/tailwindcss/commands.rb#18
    def executable(exe_path: T.unsafe(nil)); end

    # source://tailwindcss-rails//lib/tailwindcss/commands.rb#14
    def platform; end

    # source://tailwindcss-rails//lib/tailwindcss/commands.rb#69
    def watch_command(poll: T.unsafe(nil), **kwargs); end
  end
end

# raised when the tailwindcss executable could not be found where we expected it to be
class Tailwindcss::Commands::ExecutableNotFoundException < ::StandardError; end

# raised when the host platform is not supported by upstream tailwindcss's binary releases
class Tailwindcss::Commands::UnsupportedPlatformException < ::StandardError; end

class Tailwindcss::Engine < ::Rails::Engine; end

# constants describing the upstream tailwindcss project
module Tailwindcss::Upstream; end

# rubygems platform name => upstream release filename
#
# source://tailwindcss-rails//lib/tailwindcss/upstream.rb#7
Tailwindcss::Upstream::NATIVE_PLATFORMS = T.let(T.unsafe(nil), Hash)

# source://tailwindcss-rails//lib/tailwindcss/upstream.rb#4
Tailwindcss::Upstream::VERSION = T.let(T.unsafe(nil), String)

# source://tailwindcss-rails//lib/tailwindcss/version.rb#2
Tailwindcss::VERSION = T.let(T.unsafe(nil), String)
